### ISSUE TITLE
Implement MLflow for Model Experiment Tracking

### ISSUE THREAD

**Issue by Vansh290802** [Vansh290802/supply_chain_project#1]
## Overview
We need to implement MLflow to track experiments for all models in our supply chain project. This will help us monitor, compare, and reproduce our model training results across different runs.

### 1. MLflow Infrastructure Setup
- [ ] Add MLflow to requirements.txt
- [ ] Set up MLflow tracking server configuration
- [ ] Create standard experiment naming convention
- [ ] Define standard tags for experiment categorization

### 2. Model Tracking Implementation
Need to implement MLflow tracking for each model component:

#### Risk Assessment Models
- [ ] Track supplier risk model metrics
  - RMSE, MAE for disruption prediction
  - Classification metrics for risk levels
  - Feature importance scores
- [ ] Log model hyperparameters
- [ ] Save model artifacts

#### Route Optimization Models
- [ ] Track clustering model performance
  - Silhouette scores
  - Inertia metrics
  - Cluster distribution statistics
- [ ] Log optimization parameters
- [ ] Store route recommendations

#### Maintenance Prediction Models
- [ ] Track predictive maintenance metrics
  - Precision/Recall for maintenance alerts
  - Time-based prediction accuracy
- [ ] Log vehicle health scores
- [ ] Save prediction thresholds

#### External Factors Analysis Models
- [ ] Track impact analysis metrics
  - Correlation scores
  - Weather impact coefficients
  - Traffic pattern analysis
- [ ] Log analysis parameters
- [ ] Store factor importance rankings

#### Inventory Management Models
- [ ] Track inventory optimization metrics
  - Stock level prediction accuracy
  - Reorder point optimization scores
- [ ] Log optimization parameters
- [ ] Save inventory rules

### 3. Code Structure Changes

```python
# Example implementation structure
from mlflow import log_metric, log_param, log_artifacts, start_run

class ModelTracker:
    def __init__(self, experiment_name):
        self.experiment_name = experiment_name
        mlflow.set_experiment(experiment_name)

    def track_run(self, run_name, params, metrics, artifacts):
        with start_run(run_name=run_name):
            # Log parameters
            for param_name, value in params.items():
                log_param(param_name, value)
            
            # Log metrics
            for metric_name, value in metrics.items():
                log_metric(metric_name, value)
            
            # Log artifacts
            for artifact_name, artifact in artifacts.items():
                log_artifacts(artifact)
```

### 4. UI Integration
- [ ] Add MLflow UI link to project documentation
- [ ] Create standard visualization templates for each model type
- [ ] Document how to compare experiments

## Expected Benefits
1. Better model versioning and reproducibility
2. Easy comparison of different model versions and parameters
3. Centralized storage of model metrics and artifacts
4. Simplified model deployment process
5. Better collaboration through shared experiment results

## Success Criteria
- All models are tracked using MLflow
- Each run captures relevant metrics, parameters, and artifacts
- Documentation updated with MLflow usage instructions
- Team members can easily compare and analyze model runs

## Additional Notes
- Consider setting up a remote tracking server for team-wide access
- Implement automated logging for standard metrics
- Create backup procedures for experiment data

## Timeline
- Infrastructure Setup: 2 days
- Individual Model Implementation: 1-2 days per model
- Testing and Documentation: 2 days
- Total Estimated Time: ~2 weeks
